persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_type all

# MQTT (TCP)
listener 1883 0.0.0.0
protocol mqtt

# MQTT over WebSockets (para browser / dashboards)
listener 9001 0.0.0.0
protocol websockets

# DEV: simples (sem user/pass). Para produção, trocar para password_file e allow_anonymous false.
allow_anonymous true


